name: betterstreams
description: A better football streamer.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.4.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_scraper: ^0.1.4
  http: ^0.13.0
  intl: ^0.17.0
  flutter_riverpod: ^0.13.1
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
